package com.paylens.backend.model;
public enum AuditEventType { ACTION_ANALYZED, INTENT_PARSED, SIMULATION_COMPLETED, POLICY_EVALUATED, EXPLANATION_GENERATED, REVIEW_REQUESTED, REVIEW_APPROVED, REVIEW_REJECTED, ACTION_BLOCKED }
