package com.paylens.backend.model;

public enum RiskSignalType {
    LOW_LIQUIDITY,
    SAFETY_BUFFER_PRESSURE,
    UPCOMING_OBLIGATION,
    HIGH_OBLIGATION_CONCENTRATION,
    EXECUTION_FAILURE,
    RECONCILIATION_REQUIRED,
    UNKNOWN_EXECUTION,
    REVENUE_AT_RISK
}
